variables:
  PYTHON_VERSION: "3.6"
  POSTGRES_PASSWORD: password

cache:
  key: global
  paths:
    - ci-cache


before_script:
  - time source gitlab-ci-init-python.inc
      # --verbose
      # --verbose
      # --verbose


image: alliance/python:bionic


# linting
lint:
  script:
    # we install required packages so linter's isort can know is(n't) a 3rd party package
    - time pip install -r requirements.txt
    - time bin/lint.sh
#  when: manual


# unit tests
test-python-postgres:
  services:
    - postgres:12
  script:
    - pip install tox tox-factor
    - time bin/runtests.sh -f postgresql
#  when: manual


test-python-mysql:
  services:
    - alliance/mysql
  script:
    - pip install tox tox-factor
    - time bin/runtests.sh -f mysql
